"""Generate the failure matrix from the tests, so it cannot drift from reality.

A matrix maintained by hand becomes a wish list. This one is derived: every
entry points at a test that actually runs, and the generator fails if an entry
has no regression behind it.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(
    "/media/endlessblink/data/my-projects/ai-development/devops/hermes/lifeboat-live"
)
TESTS = ROOT / "tests/gateway"
OUT = ROOT / "docs/lifeboat-failure-matrix.md"

# id, what was observed, when it was seen, the task, the test file that pins it
ENTRIES = [
    ("LF-01", "Engine plumbing delivered mid-conversation: interrupt, queue, steer, compression and batching notices",
     "2026-08-22 13:46–18:26", "BUG-30", "test_lifeboat_regressions.py"),
    ("LF-02", "One hardcoded Hebrew sentence repeated verbatim across eight deliveries",
     "2026-08-22 15:25–18:30", "BUG-6", "test_lifeboat_regressions.py"),
    ("LF-03", "A reworded generic re-entry that a literal ban list could not catch",
     "2026-08-22 (acceptance example)", "BUG-6", "test_lifeboat_reentry.py"),
    ("LF-04", "A byte-identical answer delivered twice a minute apart",
     "2026-08-22 13:46 and 13:47", "BUG-30", "test_lifeboat_regressions.py"),
    ("LF-05", "A stale reply answering a message the user had already moved past",
     "2026-08-22 15:25", "BUG-30", "test_lifeboat_superseded_delivery.py"),
    ("LF-06", "Coaching shape imposed on a technical answer",
     "2026-08-22 16:13", "BUG-29", "test_lifeboat_contracts.py"),
    ("LF-07", "A pasted background-process dump read as a crisis disclosure",
     "2026-08-22 17:08", "BUG-9", "test_lifeboat_signal_provenance.py"),
    ("LF-08", "A crisis phrase the installed runtime had silently stopped recognising",
     "2026-08-22 (found in review)", "BUG-9", "test_lifeboat_regressions.py"),
    ("LF-09", "A feared reading handed back as established fact about another person",
     "2026-08-22 (found in review)", "BUG-25", "test_lifeboat_feared_premise.py"),
    ("LF-10", "A lane switch ignored, leaving a technical detour in control",
     "2026-08-22 (found in review)", "BUG-21", "test_lifeboat_modes.py"),
    ("LF-11", "Every delivery gate failing open, invisibly, because the runtime could not import them",
     "2026-08-22 (found in review)", "BUG-32", "test_lifeboat_runtime_check.py"),
    ("LF-12", "Unit tests reading the user's real conversation database",
     "2026-08-22 (found in review)", "BUG-32", "test_state_db_isolation.py"),
    ("LF-13", "Test fixture jobs written into the live cron store and executed",
     "2026-08-22 (found in review)", "BUG-32", "test_cron_store_isolation.py"),
]

missing = [e for e in ENTRIES if not (TESTS / e[4]).is_file()]
if missing:
    for entry in missing:
        print(f"FAIL {entry[0]} points at {entry[4]}, which does not exist")
    sys.exit(1)

counts = {}
for entry in ENTRIES:
    path = TESTS / entry[4]
    counts[entry[4]] = len(re.findall(r"^def test_", path.read_text(encoding="utf-8"), re.M))

rows = "\n".join(
    f"| {i} | {what} | {seen} | {task} | `{test}` | {counts[test]} |"
    for i, what, seen, task, test in ENTRIES
)

OUT.write_text(f"""# Life-Boat failure matrix

Every row is a failure that actually reached the Telegram topic or was found
while verifying a task that claimed to be finished. Each one points at a test
that runs in the suite today, and this file is generated from that list, so an
entry cannot survive its regression being deleted.

Generated by `scripts/build_failure_matrix.py`. Run it after adding a row.

| ID | What went wrong | When it was seen | Task | Regression | Tests in file |
|----|-----------------|------------------|------|------------|---------------|
{rows}

## How a row gets added

A row is added when a failure is observed in the live conversation, or found
while checking a task's acceptance. It needs the literal trigger, the time it
was seen, the task that owns it, and a test that fails before the fix and
passes after. A row without a regression behind it is a wish, and the generator
refuses to write one.

## Are the gates still reachable?

The per-row regressions prove each gate is correct. They do not prove the
gateway still calls it. `scripts/lifeboat_stress_matrix.py` drives every row
through the delivery-time function that is supposed to stop it, and
`tests/gateway/test_lifeboat_stress_matrix.py` runs it in the suite and fails
if a row in this file has neither a stress case nor a named reason it cannot
be driven here.

Three rows cannot be driven by a pure function. LF-05 needs a live turn, and
LF-12 and LF-13 are properties of the test harness itself. The harness prints
those by name rather than passing quietly over them.

## The accepted baseline and rolling back

`scripts/lifeboat_baseline.py` freezes the eight files that decide what reaches
the topic, taken from the installed runtime with a sha256 each. Reverting a
commit does not undo a bad install -- the installed tree is a separate copy, and
the gap between the two is what let a gate sit installed with no caller -- so
the baseline is content, not a revision.

    lifeboat_baseline.py verify              is the runtime what we accepted?
    lifeboat_baseline.py restore --dry-run   what would rolling back change?
    lifeboat_baseline.py restore             put the accepted bytes back
    lifeboat_baseline.py freeze --label ...  accept what is running now

Restoring never restarts the gateway; that stays deliberate.
`tests/gateway/test_lifeboat_baseline.py` exercises freeze, drift, restore and
dry-run against a temporary tree, so the rollback is tested rather than
promised.

## What this does not cover

Semantic quality across a whole conversation -- whether a reply genuinely
helped -- is not decidable by these tests. They pin deterministic invariants:
what must never be delivered, what must never be silently dropped, what must
always be recognised. Multi-turn judgement still needs a human reading real
transcripts.
""", encoding="utf-8")

total = sum(counts.values())
print(f"wrote {OUT.relative_to(ROOT)}: {len(ENTRIES)} entries, {total} tests behind them")
